version: '3.8'

services:
  app:
    image: php:8.3-fpm
    container_name: laravel-app
    volumes:
      - ./laravel:/var/www/html
    networks:
      - laravel
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    environment:
      - TZ=Asia/Jakarta
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: 300102
      MYSQL_DATABASE: landing_page
      MYSQL_USER: root
      MYSQL_PASSWORD: 300102
    ports:
      - "3307:3307"  # Menggunakan port 3307 agar tidak bentrok
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    volumes:
      - ./laravel:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - app

networks:
  laravel:

volumes:
  mysql_data: