version: "3.8"

services:
    app:
        build: .
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"
        depends_on:
            - db
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:LO8ZbD+jaM3nnGvPM2OoMVhMSnuvxpnZQE+6oJgejOE=

    db:
        image: mysql:8
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: phpmyadmin
            MYSQL_PASSWORD: "@Thebest2024"
            MYSQL_ROOT_PASSWORD: phpmyadmin
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
