version: '3.8'

services:
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: '@Thebest2024'
      MYSQL_DATABASE: 'landing_page'
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

  laravel:
    build:
      context: .
      dockerfile: dockerfile
    container_name: laravel_app
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www
    depends_on:
      - mariadb
    networks:
      - laravel_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    depends_on:
      - laravel
    networks:
      - laravel_net

volumes:
  mariadb_data:

networks:
  laravel_net:
    driver: bridge