version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    ports:
      - 9000:9000
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: